package com.mykael.prefeitura.core.timeline;

public enum TipoEventoTimeline {
	DENUNCIA_CRIADA,
	COMENTARIO_ADICIONADO,
	RESPOSTA_OFICIAL_PUBLICADA,
	STATUS_ALTERADO,
	ANEXO_ADICIONADO,
	DENUNCIA_ARQUIVADA_MODERACAO,
	COMENTARIO_REMOVIDO_MODERACAO,
	TRANSFERENCIA_SOLICITADA,
	TRANSFERENCIA_APROVADA,
	TRANSFERENCIA_RECUSADA,
	RESPONSAVEL_ALTERADO_PREFEITURA,
	CONCLUSAO_CONFIRMADA_MORADOR,
	CONCLUSAO_CONTESTADA_MORADOR
}
