package com.mykael.prefeitura.core.notificacao;

public enum TipoNotificacao {
	DENUNCIA_ATRIBUIDA,
	DENUNCIA_CONCLUIDA_AGUARDANDO_CONFIRMACAO,
	TRANSFERENCIA_SOLICITADA,
	TRANSFERENCIA_APROVADA,
	TRANSFERENCIA_RECUSADA,
	SINALIZACAO_DENUNCIA_RECEBIDA,
	MODERACAO_DENUNCIA_ARQUIVADA,
	MODERACAO_COMENTARIO_REMOVIDO,
	MODERACAO_USUARIO_ADVERTIDO,
	MODERACAO_USUARIO_SUSPENSO,
	MODERACAO_USUARIO_REATIVADO
}
